[Settings]
# Added automatically by the Netlify CLI. It has no effect during normal
# Git-backed deploys.
# ID = "Your_Site_ID"

# Redirects and headers are GLOBAL for all builds â€“ they do not get scoped to
# contexts no matter where you define them in the file.
# For context-specific rules, use _headers or _redirects files, which are
# PER-DEPLOY.

[[redirects]]
  from = "/index.html"
  to = "/"

  # The default HTTP status code is 301, but you can define a different one.
  status = 301

  # By default, redirects won't be applied if there's a file with the same
  # path as the one defined in the `from` property. Setting `force` to `true`
  # will make the redirect rule take precedence over any existing files.
  force = true

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://vue-virtual-scroll-grid.netlify.app"
  to = "https://grid.kiwiberry.nz"
  status = 301
  force = true

# Long-term cache by default.
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

# And here are the exceptions:
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "max-age=86400"

[[headers]]
  for = "/sitemap.txt"
  [headers.values]
    Cache-Control = "max-age=86400"
